; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno, esp32dev

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = 
    -D LED_BUILTIN=13 
    -D BLINK_INTERVAL_MS=1000
upload_port = /dev/cu.usbmodem111101

test_filter =
    test_embedded_blink

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = /dev/cu.usbserial-0001
upload_protocol = esptool ; Default

monitor_speed = 115200

build_type = debug
build_flags = 
    -D LED_BUILTIN=2 
    -D BLINK_INTERVAL_MS=1000

test_filter =
    test_embedded_blink

[env:native]
platform = native
test_framework = unity
test_filter =
    test_native_blink
build_flags =
    -D UNIT_TEST